#!/bin/sh
# Regenerate requirements.txt: the exact runtime closure the image installs with --no-deps.
#
# Resolves pyproject.toml's loose ranges from scratch in a linux/amd64 container (the
# image's platform, L07), drops the transitive packages cadquery declares but screw never
# imports, proves what is left can still build a part and answer an HTTP request, and
# freezes that.
set -eu
cd "$(dirname "$0")/.."
PLATFORM="${PLATFORM:-linux/amd64}"

# Keeping these costs ~550 MB and buys nothing: VTK viewers, DXF export, the assembly
# solver's plotting, matplotlib. What must stay, and why:
#   vtk       OCP links libvtkWrappingPythonCore -- OCP will not import without it
#   casadi nlopt ezdxf pyparsing multimethod runtype   cadquery imports these eagerly
#   idna      anyio needs it, and only an HTTP request finds that out, which is why
#             docker/smoke.py drives the ASGI app instead of just calling export()
# Carried from spur unchanged (RESEARCH A6); docker/smoke.py below is the proof it still
# holds for the cadquery in this closure.
PRUNE="trame trame-client trame-common trame-components trame-server trame-vtk
trame-vuetify wslink numba llvmlite matplotlib contourpy cycler kiwisolver pillow
scipy aiohttp aiosignal frozenlist multidict yarl propcache attrs msgpack"

docker build --platform "$PLATFORM" -q -t screw:resolve - >/dev/null <<'DOCKER'
FROM python:3.12-slim-bookworm
RUN apt-get update \
 && apt-get install -y --no-install-recommends libgl1 libx11-6 libexpat1 \
 && rm -rf /var/lib/apt/lists/*
DOCKER

frozen=$(docker run --rm --platform "$PLATFORM" -v "$PWD:/src:ro" -e PRUNE="$PRUNE" \
  screw:resolve sh -c '
    set -eu
    pip install -q --no-cache-dir /src
    pip uninstall -y -q $PRUNE >/dev/null 2>&1 || true
    python /src/docker/smoke.py >&2
    pip freeze | grep -v "^screw" | sort')

cat > requirements.txt <<HEADER
# The exact runtime closure the Docker image installs, with --no-deps (L07).
#
# Generated by docker/refresh-requirements.sh -- regenerate, never hand-edit: with
# --no-deps pip will not tell you when a hand-bumped version breaks the closure.
# pyproject.toml keeps loose ranges for installing into your own environment.
#
# Also the pip constraint every make venv and CI install reads, so the cadquery /
# cadquery-ocp pair cannot move under the tests. The gate's own tools (ruff, mypy,
# pytest, import-linter, pre-commit) are deliberately not in it and float (D-17, L08).
HEADER
printf '%s\n' "$frozen" >> requirements.txt
echo "wrote requirements.txt ($(grep -c '==' requirements.txt) packages)" >&2
echo "now verify the image: make smoke" >&2
